name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          RELEASE_VERSION="${tag}" make github-draft-release
